# Generated by Django 4.2.6 on 2023-11-08 17:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2023)])),
                ('fuel', models.CharField(blank=True, max_length=30)),
                ('gear_box', models.CharField(blank=True, max_length=30)),
                ('car_type', models.CharField(blank=True, max_length=30)),
                ('engine_volume', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('drive_unit', models.CharField(blank=True, max_length=30)),
                ('body_type', models.CharField(blank=True, max_length=20)),
                ('region_of_car', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=20)),
                ('about', models.CharField(blank=True, max_length=10000)),
                ('this_user_name', models.CharField(default=None, max_length=100, null=True)),
                ('this_user_phone', models.CharField(blank=True, max_length=100)),
                ('this_user_email', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_requests',
                'ordering': ['id'],
            },
        ),
    ]
