# Generated by Django 4.2.6 on 2023-11-08 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequestmodel',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='engine_volume',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(10.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='vin',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('\\b[(A-H|J-N|P|R-Z|0-9)]{17}\\b', 'OEM must be 17 symbols')]),
        ),
    ]
