# Generated by Django 4.2.6 on 2023-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0003_partrequestmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequestmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
