# Generated by Django 4.2.6 on 2023-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0003_alter_partrequestmodel_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='about',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='engine_volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='oem',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='vin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
