# Generated by Django 4.2.6 on 2023-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0004_partrequestmodel_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('toCur', models.CharField(max_length=30)),
                ('fromCur', models.CharField(max_length=30)),
                ('buy', models.IntegerField()),
                ('sale', models.IntegerField()),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
