# Generated by Django 4.2.6 on 2023-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0004_alter_partrequestmodel_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='engine_volume',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
