# Generated by Django 4.2.6 on 2023-11-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0005_alter_partrequestmodel_engine_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrequestmodel',
            options={'ordering': ['id']},
        ),
    ]
