# Generated by Django 4.2.6 on 2023-11-02 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_requests', '0006_alter_partrequestmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequestmodel',
            name='body_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='car_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='drive_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='fuel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='gear_box',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='part_condition',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='part_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='region_of_car',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
    ]
