# Generated by Django 4.2.6 on 2023-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0007_alter_partrequestmodel_region_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Седан', 'sedan'), ('Хетчбек', 'hatchback'), ('Універсал', 'wagon'), ('Купе', 'coupe'), ('Кабріолет', 'convertible'), ('Спорткар', 'sports-car'), ('Позашляховик', 'suv'), ('Кросовер', 'crossover'), ('Мінівен', 'minivan'), ('Пікап', 'pickup'), ('Фургон', 'van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='car_brand',
            field=models.CharField(choices=[('Acura', 'acura'), ('Alfa Romeo', 'alfa-romeo'), ('Audi', 'audi'), ('BMW', 'bmw'), ('Chevrolet', 'chevrolet'), ('Citroen', 'citroen'), ('Dacia', 'dacia'), ('Fiat', 'fiat'), ('Ford', 'ford'), ('Honda', 'honda'), ('Hyundai', 'hyundai'), ('Jaguar', 'jaguar'), ('Jeep', 'jeep'), ('Kia', 'kia'), ('Land Rover', 'land-rover'), ('Lexus', 'lexus'), ('Mazda', 'mazda'), ('Mercedes-Benz', 'mercedes-benz'), ('Mitsubishi', 'mitsubishi'), ('Nissan', 'nissan'), ('Opel', 'opel'), ('Peugeot', 'peugeot'), ('Porsche', 'porsche'), ('Renault', 'renault'), ('Seat', 'seat'), ('Skoda', 'skoda'), ('Subaru', 'subaru'), ('Suzuki', 'suzuki'), ('Tesla', 'tesla'), ('Toyota', 'toyota'), ('Volkswagen', 'volkswagen'), ('Volvo', 'volvo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='drive_unit',
            field=models.CharField(blank=True, choices=[('Front', 'front'), ('Rear', 'rear'), ('Full', 'full')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Gas', 'gas'), ('Diesel', 'diesel'), ('LPG', 'lpg')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='gear_box',
            field=models.CharField(blank=True, choices=[('Automatic', 'automatic'), ('Manual', 'manual'), ('Variator', 'variator')], max_length=30),
        ),
    ]
