# Generated by Django 4.2.6 on 2023-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0007_partrequestmodel_body_type_partrequestmodel_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequestmodel',
            name='this_user_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='this_user_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partrequestmodel',
            name='this_user_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='region_of_car',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
