# Generated by Django 4.2.6 on 2023-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0009_partrequestmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='car_brand',
            field=models.CharField(max_length=30),
        ),
    ]
