# Generated by Django 4.2.6 on 2023-11-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0011_partrequestmodel_user_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='car_brand',
            field=models.CharField(choices=[('Acura', 'acura'), ('Alfa Romeo', 'alfa-romeo'), ('Audi', 'audi'), ('BMW', 'bmw'), ('Chevrolet', 'chevrolet'), ('Citroen', 'citroen'), ('Dacia', 'dacia'), ('Fiat', 'fiat'), ('Ford', 'ford'), ('Honda', 'honda'), ('Hyundai', 'hyundai'), ('Jaguar', 'jaguar'), ('Jeep', 'jeep'), ('Kia', 'kia'), ('Land Rover', 'land-rover'), ('Lexus', 'lexus'), ('Mazda', 'mazda'), ('Mercedes-Benz', 'mercedes-benz'), ('Mitsubishi', 'mitsubishi'), ('Nissan', 'nissan'), ('Opel', 'opel'), ('Peugeot', 'peugeot'), ('Porsche', 'porsche'), ('Renault', 'renault'), ('Seat', 'seat'), ('Skoda', 'skoda'), ('Subaru', 'subaru'), ('Suzuki', 'suzuki'), ('Tesla', 'tesla'), ('Toyota', 'toyota'), ('Volkswagen', 'volkswagen'), ('Volvo', 'volvo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
