# Generated by Django 4.2.6 on 2023-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0012_alter_partrequestmodel_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partrequestmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='partrequestmodel',
            name='this_user_email',
        ),
        migrations.RemoveField(
            model_name='partrequestmodel',
            name='this_user_name',
        ),
        migrations.RemoveField(
            model_name='partrequestmodel',
            name='this_user_phone',
        ),
        migrations.RemoveField(
            model_name='partrequestmodel',
            name='user_attempts',
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='about',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='body_type',
            field=models.CharField(choices=[('Седан', 'sedan'), ('Хетчбек', 'hatchback'), ('Універсал', 'wagon'), ('Купе', 'coupe'), ('Кабріолет', 'convertible'), ('Спорткар', 'sports-car'), ('Позашляховик', 'suv'), ('Кросовер', 'crossover'), ('Мінівен', 'minivan'), ('Пікап', 'pickup'), ('Фургон', 'van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='drive_unit',
            field=models.CharField(choices=[('Front', 'front'), ('Rear', 'rear'), ('Full', 'full')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='fuel',
            field=models.CharField(choices=[('Gas', 'gas'), ('Diesel', 'diesel'), ('LPG', 'lpg')], max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='gear_box',
            field=models.CharField(choices=[('Automatic', 'automatic'), ('Manual', 'manual'), ('Variator', 'variator')], max_length=30),
        ),
    ]
