# Generated by Django 4.2.6 on 2023-11-13 18:37

import core.services.upload_avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0014_remove_partrequestmodel_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequestmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar.upload_photo_for_request),
        ),
    ]
