CAR_BRANDS = (
    ('Acura', 'acura'),
    ('Alfa Romeo', 'alfa-romeo'),
    ('Audi', 'audi'),
    ('BMW', 'bmw'),
    ('Chevrolet', 'chevrolet'),
    ('Citroen', 'citroen'),
    ('Dacia', 'dacia'),
    ('Fiat', 'fiat'),
    ('Ford', 'ford'),
    ('Honda', 'honda'),
    ('Hyundai', 'hyundai'),
    ('Jaguar', 'jaguar'),
    ('Jeep', 'jeep'),
    ('Kia', 'kia'),
    ('Land Rover', 'land-rover'),
    ('Lexus', 'lexus'),
    ('Mazda', 'mazda'),
    ('Mercedes-Benz', 'mercedes-benz'),
    ('Mitsubishi', 'mitsubishi'),
    ('Nissan', 'nissan'),
    ('Opel', 'opel'),
    ('Peugeot', 'peugeot'),
    ('Porsche', 'porsche'),
    ('Renault', 'renault'),
    ('Seat', 'seat'),
    ('Skoda', 'skoda'),
    ('Subaru', 'subaru'),
    ('Suzuki', 'suzuki'),
    ('Tesla', 'tesla'),
    ('Toyota', 'toyota'),
    ('Volkswagen', 'volkswagen'),
    ('Volvo', 'volvo'),
)
CAR_BODY_TYPES = (
    ('Седан', 'sedan'),
    ('Хетчбек', 'hatchback'),
    ('Універсал', 'wagon'),
    ('Купе', 'coupe'),
    ('Кабріолет', 'convertible'),
    ('Спорткар', 'sports-car'),
    ('Позашляховик', 'suv'),
    ('Кросовер', 'crossover'),
    ('Мінівен', 'minivan'),
    ('Пікап', 'pickup'),
    ('Фургон', 'van'),
)
