REGIONS = (
    ('АР Крим', 'arkrym'),
    ('Вінницька', 'vinnytska'),
    ('Волинська', 'volynska'),
    ('Дніпропетровська', 'dnipropetrovska'),
    ('Донецька', 'donetska'),
    ('Житомирська', 'zhytomyrska'),
    ('Закарпатська', 'zakarpatska'),
    ('Івано-Франківська', 'ivano-frankivska'),
    ('Київська', 'kyivska'),
    ('Кіровоградська', 'kirovohradska'),
    ('Луганська', 'luhanska'),
    ('Львівська', 'lvivska'),
    ('Миколаївська', 'mykolaivska'),
    ('Одеська', 'odeska'),
    ('Полтавська', 'poltavska'),
    ('Рівненська', 'rivnenska'),
    ('Сумська', 'sumska'),
    ('Тернопільська', 'ternopilska'),
    ('Харківська', 'kharkivska'),
    ('Херсонська', 'khersonska'),
    ('Хмельницька', 'khmelnytska'),
    ('Черкаська', 'cherkaska'),
    ('Чернівецька', 'chernivetska'),
    ('Чернігівська', 'chernihivska')
)
