# Generated by Django 4.2.6 on 2023-11-02 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usermodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(default=1, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', 'Phone must be correct')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s]){8,128}$', 'Password must contain 1 number (0-9), 1 uppercase letters, 1 lowercase letters, 1 non-alpha numeric number, 8-16 characters with no space')]),
        ),
    ]
