# Generated by Django 4.2.6 on 2023-11-02 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profilemodel_age_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', 'Phone must be correct')]),
        ),
    ]
