# Generated by Django 4.2.6 on 2023-11-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usermodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='is_customer',
            new_name='is_premium',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
