# Generated by Django 4.2.6 on 2023-11-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_is_customer_usermodel_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='requests_count',
            field=models.IntegerField(default=0),
        ),
    ]
