# Generated by Django 4.2.6 on 2023-11-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usermodel_requests_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='premium_till',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
